/** Component V2 message for displaying Terms and Conditions during setup */

import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ContainerBuilder, MessageFlags, SeparatorBuilder, TextDisplayBuilder } from "discord.js";
import { Urls } from "../../bot/config";
import { UniversalMessage } from "../../bot/types";

function termsView(): UniversalMessage {
    const playtestNote = new TextDisplayBuilder()
        .setContent(
            `⚠️ **Playtest Version Notice**\n` +
            `This is a playtest version of the Truth or Dare bot. When the playtest completes on <t:1775343600:F>, all data from the playtest period will be reset. You will need to run setup again after the reset. \n\n During the playtest, you are encouraged to push every button and try every feature. You will not be banned or penalised for doing so (unless you break Discord's ToS or the law, of course). \n\n If you have any feedback, please join our support server and let us know!`
        );

    const title = new TextDisplayBuilder()
        .setContent(`## **Accept these Terms and Conditions to proceed**`);

    const subtitle = new TextDisplayBuilder()
        .setContent(`Type /accept-terms to accept these terms and grant access to the bot`);

    const acknowledgment = new TextDisplayBuilder()
        .setContent(
            `**1. Acknowledgment**\n` +
            `You the Administrator of this server acknowledge and understand that Truth or Dare Online is an adult game with adult content not intended for anybody under 18.`
        );

    const precautions = new TextDisplayBuilder()
        .setContent(
            `**2. Precautions for Under 18s**\n` +
            `You agree that you will take every reasonable precaution to prevent children under the age of 18 from viewing any channels this bot is used in.`
        );

    const reporting = new TextDisplayBuilder()
        .setContent(
            `**3. Reporting**\n` +
            `You understand that any user can report your server for allowing under 18's to use or view content generated by this bot or its users.`
        );

    const investigation = new TextDisplayBuilder()
        .setContent(
            `**4. Investigation**\n` +
            `You agree that if such a report is submitted, a member of the bot's moderation team may investigate your server.`
        );

    const consequences = new TextDisplayBuilder()
        .setContent(
            `**5. Consequences**\n` +
            `You understand that your server could be banned from using the bot and reported to Discord's Trust and Safety team if a member of the moderation team finds you to be breaching these terms, Discord ToS, or the law.`
        );

    const data = new TextDisplayBuilder()
        .setContent(
            `**6. Data**\n` +
            `You agree to allow the bot to store some basic information about the community for moderation purposes. Your community ID number, and your community's name.`
        );

    const links = new TextDisplayBuilder()
        .setContent(
            `**Links**\n\n` +
            `**For updates and help**\t\t\t\t **Got your own community?**\n` +
            `[Join Our Support Server](${Urls.OFFICIAL_SERVER})\t\t\t[Add The Bot](${Urls.ADD_BOT})\n\n` +
            `[Privacy Policy](${Urls.PRIVACY_POLICY})  •  [Terms of Service](${Urls.TERMS_OF_SERVICE})`
        );

    // Build container
    const container = new ContainerBuilder()
        .addTextDisplayComponents(playtestNote)
        .addSeparatorComponents(new SeparatorBuilder())
        .addTextDisplayComponents(title)
        .addSeparatorComponents(new SeparatorBuilder())
        .addTextDisplayComponents(subtitle, acknowledgment, precautions, reporting, investigation, consequences, data)
        .addSeparatorComponents(new SeparatorBuilder())
        .addTextDisplayComponents(links);

    // Create Accept/Decline buttons
    const acceptButton = new ButtonBuilder()
        .setCustomId('setup_acceptTerms')
        .setLabel('Accept')
        .setStyle(ButtonStyle.Success);

    const declineButton = new ButtonBuilder()
        .setCustomId('setup_declineTerms')
        .setLabel('Decline')
        .setStyle(ButtonStyle.Danger);

    const buttonRow = new ActionRowBuilder<ButtonBuilder>()
        .addComponents(acceptButton, declineButton);

    const message: UniversalMessage = {
        flags: MessageFlags.IsComponentsV2,
        components: [container, buttonRow],
    };

    return message;
}

export { termsView };
